### ISSUE TITLE
mqtt support

### ISSUE THREAD

**Issue by michalk-k** [prusa3d/Prusa-Connect-Local#105]
Hello guys
When http API is usefull in some circumstances, fails in others. For example it's unavailable when device is turned off. Also requires polling with some frequency which one might find suboptimal.

I suggest to consider mqtt as industry proven standard of API between systems. 

The monitoring of printer(s) would be more efficient and reliable with mqtt use of mqtt

with regards

**Comment by JakubSilar3D** [comment]
Thank you for the advice - we are considering the pros and cons - adding another interface has the costs of extra complexity.
