### ISSUE TITLE
Add upload gcode to USB stick

### ISSUE THREAD

**Issue by hawwwran** [prusa3d/Prusa-Connect-Local#20]
Possibility to upload gcode file over web interface would be very useful. Simple file manager to be able to upload gcode to usb in the MINI would be the best, but even simple upload to root would help a lot.

**Comment by JakoobCZ** [comment]
Hi Hawwwran,
thanks for the suggestion, this feature is on our to-do list. However, it requires some work from our developers as we also need to include security measures. Stay tuned for the upcoming releases :)
